---
- name: Install webserver packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'nginx' ]

- name: Deploy website
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  tags: [ 'update', 'sync' ]
