---
- name: Include all .yaml files in vars directory
  ansible.builtin.include_vars:
    dir: vars
    extensions:
      - 'yaml'
      - 'yml'

- name: Install Base Packages
  ansible.builtin.package:
    name: "{{base_packages}}"
    state: present
