---
# tasks file for zz_postsetup

- name: Set up ansible-pull to run every hour
  ansible.builtin.cron:
    name: "check dirs"
    minute: "0"
    job: "/usr/bin/ansible-pull --url=https://github.com/cjestel/ansible_server_roles.git dbtune.yaml >> /var/log/ansible-pull 2>&1"

- blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
  loop: "{{ ap_logrotate_confd }}"
